{"uuid": "716d1e4c-6444-468b-9f90-272e7f450d72", "children": ["3d192407-c03f-47ce-97fc-beaa773172d8", "ded104c2-4515-4cab-aa06-9588075c838f", "eef5cbf2-473f-42b6-90d7-ded5018a110b", "9ec13eaf-c850-438d-afa8-e8dcf760b2e0", "96f32ece-cf63-4a9c-8832-1c3f5fcb9653", "46c2ff2a-0be6-45a2-950e-87db46eb23bc", "5f2eb695-e8e4-47b7-97cc-e4b1a660f49a"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom chrome not reachable\n  (Session info: chrome=84.0.4147.89)\n\n", "trace": "  File \"e:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\web_2020_03\\case\\conftest.py\", line 13, in driver\n    _driver = webdriver.Chrome()\n  File \"e:\\python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"e:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"e:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"e:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"e:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595582034799, "stop": 1595582049969}], "start": 1595582034799, "stop": 1595582052586}